# In the Name of God, the Most Compassionate, Most Merciful


import re


class Hash:
    def __init__(self, pattern, name, family, popularity, source=None):
        self.pattern = re.compile(pattern)
        self.name = name
        self.family = family
        self.popularity = popularity
        self.source = source


POPULARITY_RANKING = {
    "Very High": 8,
    "High": 7,
    "Moderate/High": 6,
    "Growing": 5,
    "Moderate": 4,
    "Low/Moderate": 3,
    "Low": 2,
    "Very Low": 1,
}

HASH_DATA = (
    Hash(
        r"^[a-fA-F0-9]{2}$",
        "CRC-8 (Generic)",
        "Error Detection Checksum",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{2}$",
        "CRC-8/SAE-J1850",
        "Error Detection Checksum",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{2}$",
        "CRC-8/MAXIM (MAXIM-DOW)",
        "Error Detection Checksum",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{2}$",
        "CRC-8/CDMA2000",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{2}$",
        "CRC-8/DARC",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{2}$",
        "CRC-8/DVB-S2",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{2}$",
        "CRC-8/EBU (AES/EBU)",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{2}$",
        "CRC-8/I-CODE",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{2}$",
        "CRC-8/ITU (CRC-8/ATM)",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{2}$",
        "CRC-8/ROHC",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{2}$",
        "CRC-8/WCDMA",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{2}$",
        "Fletcher-8",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{4}$",
        "CRC-16 (Generic)",
        "Error Detection Checksum",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{4}$",
        "CRC-16/CCITT (CRC-16/CCITT-FALSE)",
        "Error Detection Checksum",
        POPULARITY_RANKING["Very High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{4}$",
        "CRC-16/ARC (CRC-16/IBM or CRC-16/LHA)",
        "Error Detection Checksum",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{4}$",
        "CRC-16/MODBUS",
        "Error Detection Checksum",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{4}$",
        "CRC-16/XMODEM",
        "Error Detection Checksum",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{4}$",
        "CRC-16/USB",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{4}$",
        "CRC-16/DNP",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{4}$",
        "CRC-16/KERMIT",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{4}$",
        "CRC-16/MCRF4XX",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{4}$",
        "CRC-16/T10-DIF",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{4}$",
        "Fletcher-16",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{6}$",
        "CRC-24 (OpenPGP)",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate/High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{6}$",
        "CRC-24/BLE",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{6}$",
        "CRC-24/FLEXRAY-A",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{6}$",
        "CRC-24/FLEXRAY-B",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{6}$",
        "CRC-24/LTE-A",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{6}$",
        "CRC-24/LTE-B",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{6}$",
        "CRC-24/INTERLAKEN",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{6}$",
        "CRC-24/OS-9",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{8}$",
        "CRC-32 (Standard/ISO-HDLC)",
        "Error Detection Checksum",
        POPULARITY_RANKING["Very High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{8}$",
        "CRC-32/BZIP2",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{8}$",
        "CRC-32C (Castagnoli)",
        "Error Detection Checksum",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{8}$",
        "CRC-32/MPEG-2",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{8}$",
        "CRC-32/JAMCRC",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{8}$",
        "Adler-32",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{8}$",
        "Fletcher-32",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{8}$",
        "MurmurHash3 (32-bit variant)",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{8}$",
        "FNV-1/FNV-1a (32-bit)",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{8}$",
        "xxHash32",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{8}$",
        "CityHash32",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{8}$",
        "Jenkins hash (one-at-a-time, 32-bit)",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{16}$",
        "CRC-64/XZ",
        "Error Detection Checksum",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{16}$",
        "CRC-64/ECMA-182",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{16}$",
        "CRC-64/GO-ISO",
        "Error Detection Checksum",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{16}$",
        "xxHash64",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["Very High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{16}$",
        "FNV-1/FNV-1a (64-bit)",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{16}$",
        "MurmurHash3 (64-bit / x64 variant)",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{16}$",
        "CityHash64",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{16}$",
        "SipHash (64-bit output)",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{16}$",
        "FarmHash64",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{32}$",
        "MD5",
        "Cryptographic Hash",
        POPULARITY_RANKING["Very High"],
    ),
    Hash(r"^[a-fA-F0-9]{32}$", "MD4", "Cryptographic Hash", POPULARITY_RANKING["Low"]),
    Hash(
        r"^[a-fA-F0-9]{32}$",
        "RIPEMD-128",
        "Cryptographic Hash",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{32}$",
        "Tiger-128 (truncated)",
        "Cryptographic Hash",
        POPULARITY_RANKING["Very Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{32}$",
        "Haval-128",
        "Cryptographic Hash",
        POPULARITY_RANKING["Very Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{32}$",
        "MurmurHash3 (128-bit variant, x64)",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{32}$",
        "CityHash128",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{32}$",
        "FarmHash128",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{32}$",
        "xxHash128 (XXH3-128)",
        "Non-Cryptographic Hash",
        POPULARITY_RANKING["Growing"],
    ),
    Hash(
        r"^[a-fA-F0-9]{32}$", "NTLM", "Cryptographic Hash", POPULARITY_RANKING["High"]
    ),
    Hash(
        r"^[a-fA-F0-9]{40}$",
        "SHA-1",
        "Cryptographic Hash",
        POPULARITY_RANKING["Very High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{40}$",
        "RIPEMD-160",
        "Cryptographic Hash",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{40}$",
        "Tiger-160 (truncated)",
        "Cryptographic Hash",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{40}$",
        "HAS-160",
        "Cryptographic Hash",
        POPULARITY_RANKING["Very Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{56}$",
        "SHA-224",
        "Cryptographic Hash",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{56}$",
        "SHA3-224",
        "Cryptographic Hash",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{56}$",
        "RIPEMD-224",
        "Cryptographic Hash",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{56}$",
        "HAVAL-224",
        "Cryptographic Hash",
        POPULARITY_RANKING["Very Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{64}$",
        "SHA-256",
        "Cryptographic Hash",
        POPULARITY_RANKING["Very High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{64}$",
        "SHA3-256",
        "Cryptographic Hash",
        POPULARITY_RANKING["Moderate/High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{64}$",
        "BLAKE2s",
        "Cryptographic Hash",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{64}$",
        "BLAKE3",
        "Cryptographic Hash",
        POPULARITY_RANKING["Growing"],
    ),
    Hash(
        r"^[a-fA-F0-9]{64}$",
        "RIPEMD-256",
        "Cryptographic Hash",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{64}$",
        "GOST R 34.11-2012 (Streebog-256)",
        "Cryptographic Hash",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{64}$",
        "Whirlpool (truncated)",
        "Cryptographic Hash",
        POPULARITY_RANKING["Very Low"],
    ),
    Hash(r"^[a-fA-F0-9]{64}$", "SM3", "Cryptographic Hash", POPULARITY_RANKING["Low"]),
    Hash(
        r"^[a-fA-F0-9]{80}$",
        "RIPEMD-320",
        "Cryptographic Hash",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{96}$",
        "SHA-384",
        "Cryptographic Hash",
        POPULARITY_RANKING["Moderate/High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{96}$",
        "SHA3-384",
        "Cryptographic Hash",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{96}$",
        "Whirlpool (truncated)",
        "Cryptographic Hash",
        POPULARITY_RANKING["Very Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{96}$",
        "Skein-384",
        "Cryptographic Hash",
        POPULARITY_RANKING["Very Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{128}$",
        "SHA-512",
        "Cryptographic Hash",
        POPULARITY_RANKING["Very High"],
    ),
    Hash(
        r"^[a-fA-F0-9]{128}$",
        "SHA3-512",
        "Cryptographic Hash",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{128}$",
        "Whirlpool",
        "Cryptographic Hash",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{128}$",
        "BLAKE2b",
        "Cryptographic Hash",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^[a-fA-F0-9]{128}$",
        "Skein-512",
        "Cryptographic Hash",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[a-fA-F0-9]{128}$",
        "GOST R 34.11-2012 (Streebog-512)",
        "Cryptographic Hash",
        POPULARITY_RANKING["Low"],
    ),
)

PASSWORD_HASH_DATA = (
    Hash(
        r"^\$2[abxy]?\$(?:0[4-9]|[12][0-9]|3[01])\$[a-zA-Z0-9./]{53}$",
        "bcrypt",
        "Password Hashing Function",
        POPULARITY_RANKING["Very High"],
    ),
    Hash(
        r"^\$argon2(i|d|id)\$v=\d+\$m=\d+,t=\d+,p=\d+\$[a-zA-Z0-9+/]+={0,2}\$[a-zA-Z0-9+/]+={0,2}$",
        "Argon2",
        "Password Hashing Function",
        POPULARITY_RANKING["Very High"],
    ),
    Hash(
        r"^pbkdf2_(?:sha256|sha512)\$\d+\$[a-zA-Z0-9+/=]+\$[a-zA-Z0-9+/=]+$",
        "PBKDF2 (Django-style)",
        "Password Hashing Function",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^\$pbkdf2(-sha1|-sha256|-sha512)?\$\d+\$[a-zA-Z0-9./+]+\$[a-zA-Z0-9./+]+$",
        "PBKDF2 (crypt-style)",
        "Password Hashing Function",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^\$(?:y|7)\$[a-zA-Z0-9./]+\$[a-zA-Z0-9./]+\$[a-zA-Z0-9./]+$",
        "yescrypt",
        "Password Hashing Function",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^\$scrypt\$(?:ln=\d+,r=\d+,p=\d+|N=\d+,r=\d+,p=\d+)\$[a-zA-Z0-9+/=]+\$[a-zA-Z0-9+/=]+$",
        "scrypt",
        "Password Hashing Function",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^\$6\$(rounds=\d+\$)?[./a-zA-Z0-9]{1,16}\$[./a-zA-Z0-9]{86}$",
        "SHA-512-crypt",
        "Password Hashing Function",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^\$5\$(rounds=\d+\$)?[./a-zA-Z0-9]{1,16}\$[./a-zA-Z0-9]{43}$",
        "SHA-256-crypt",
        "Password Hashing Function",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^\$1\$[./a-zA-Z0-9]{1,8}\$[./a-zA-Z0-9]{22}$",
        "MD5-crypt",
        "Password Hashing Function",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^[./a-zA-Z0-9]{13}$",
        "Traditional DES crypt",
        "Password Hashing Function",
        POPULARITY_RANKING["Very Low"],
    ),
    Hash(
        r"^\$lyra2\$t=\d+,m=\d+,p=\d+\$[a-zA-Z0-9+/=]+\$[a-zA-Z0-9+/=]+$",
        "Lyra2",
        "Password Hashing Function",
        POPULARITY_RANKING["Very Low"],
    ),
    Hash(
        r"^\$2[ay]\$[a-zA-Z0-9./]{53}$",
        "bcrypt (PHP)",
        "Password Hashing Function (PHP)",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^\$P\$[a-zA-Z0-9./]{31}$",
        "phpass (WordPress)",
        "Password Hashing Function",
        POPULARITY_RANKING["High"],
    ),
    Hash(
        r"^argon2\$[a-zA-Z0-9+/=]+\$[a-zA-Z0-9+/=]+$",
        "Argon2 (Django)",
        "Password Hashing Function",
        POPULARITY_RANKING["Moderate"],
    ),
    Hash(
        r"^\{[A-Z]+\}[a-zA-Z0-9+/=]+$",
        "LDAP Hash",
        "Password Hashing Function",
        POPULARITY_RANKING["Low/Moderate"],
    ),
    Hash(
        r"^\*[a-fA-F0-9]{40}$",
        "MySQL Password",
        "Database Password Hash",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^md5[a-fA-F0-9]{32}$",
        "PostgreSQL MD5",
        "Database Password Hash",
        POPULARITY_RANKING["Low"],
    ),
    Hash(
        r"^\{bcrypt\}[a-zA-Z0-9./]{60}$",
        "Spring Security BCrypt",
        "Password Hashing Function",
        POPULARITY_RANKING["Moderate"],
    ),
)
